services:
  mysql:
    container_name: mysql-sql-bsn
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: TAHAtaha
      MYSQL_DATABASE: itsupportapp
      MYSQL_USER: root
      MYSQL_PASSWORD: TAHAtaha
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    container_name: itsupport-app
    build:
      context: .
    ports:
      - "8088:8088"
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local
